# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\OthersProject\107Came\interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(612, 504)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.btn_start = QtWidgets.QPushButton(Form)
        self.btn_start.setObjectName("btn_start")
        self.gridLayout.addWidget(self.btn_start, 1, 0, 1, 1)
        self.btn_quit = QtWidgets.QPushButton(Form)
        self.btn_quit.setObjectName("btn_quit")
        self.gridLayout.addWidget(self.btn_quit, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_start.setText(_translate("Form", "启动"))
        self.btn_quit.setText(_translate("Form", "关闭"))
